import GoogleServiceGatewayCore

public typealias AuthExecution = GoogleServiceGatewayCore.AuthExecution
public typealias AuthAdapter = GoogleServiceGatewayCore.AuthAdapter
public typealias InteractiveOAuthAuthorizer = GoogleServiceGatewayCore.InteractiveOAuthAuthorizer
